Updates Submodules to latest
GENIVI/vehicle_signal_specification pull request #178
Opened 2020-08-21 09:35 UTC by Floix

Updates Submodules to latest instead of latest at the time of the last main repository commit.

Added installation of pip requirements during installation.

2020-08-24 07:55 UTC, Floix commented on Makefile
> +	git submodule foreach git pull origin master
I updated the make file accordingly

2020-08-24 12:07 UTC, gunnarx commented on Makefile
> +	git submodule foreach git pull origin master
I'm not convinced of this yet.  I continued the discussion in https://github.com/GENIVI/vss-tools/issues/10 where we have the context.

2020-08-24 12:20 UTC, gunnarx requested changes
Formal review added, see other comments for details

2020-08-24 12:20 UTC, gunnarx commented on Makefile
> +	git submodule foreach git pull origin master
> I updated the make file accordingly

@Floix I don't see that change, did you push?

2020-08-26 09:42 UTC, danielwilms commented
After yesterdays discussion, I would use the reference to the tools, which is defined in the submodule and update that accordingly instead of always using simply the latest version. But the extension to run pip with the requirements file makes sense for me.

2020-09-01 17:03 UTC, gunnarx commented
I would fix it but by convention I don't force push to update other people's PRs if they are sent from their master branch.

2020-09-01 17:16 UTC, danielwilms commented
#184 will update the submodules, so I'll close this one.

2020-09-01 17:16 UTC, closed without merging